name: different triggers
on:
    push:
      branches:
      - "feature1/*"

    pull_request:
      paths:
      - "03-core-features/filters/*.md"
      - "!03-core-features/filters/*.txt"

    schedule:
    - cron: "0 0 * * *" # Midnight UTC

    workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"