name: Learning Scopes
on: 
    workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-latest
    # We map the external GitHub settings into the Job
    outputs:
      pass_status: ${{ steps.check-vars.outputs.status }}
    
    steps:
      - name: Check GitHub Vars and Secrets
        id: check-vars
        run: |
          echo "The region from GitHub Vars is: ${{ vars.APP_REGION }}"
          echo "The secret is: ${{ secrets.MY_PASSWORD }}" # This will show as ***
          
          # Logic to pass to next job
          if [ "${{ vars.APP_REGION }}" == "central-india" ]; then
            echo "status=REGION_MATCH" >> "$GITHUB_OUTPUT"
          fi

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: Final Result
        run: |
          echo "Producer status was: ${{ needs.producer.outputs.pass_status }}"